### ISSUE TITLE
ERROR?

### ISSUE THREAD

**Issue by DoPaminexL** [UtterVitriol/ReadyOrNot#1]
I am a beginner and after pulling your GitHub project, I am unable to compile it. My environment is win11,22h, vs2022. My common errors after compilation are: 1. syntax error 2. type error 3. unused variable 4... 5

**Comment by DoPaminexL** [comment]
![{BDAC78EC-3D66-45fa-9893-6A512915BA4E}](https://github.com/UtterVitriol/ReadyOrNot/assets/111892202/ca1a1bc9-e16b-40a1-a8ec-c86b24e570e2)
errorphpoto

**Comment by UtterVitriol** [comment]
I cannot recreate that error.
You could try including imgui.h in Game.h
Note that this code isn't updated to the newest version of the game.

**Comment by DoPaminexL** [comment]
> 我无法重现该错误。您可以尝试在 Game.h 中包含 imgui.h 请注意，此代码不会更新到游戏的最新版本。
I am a beginner Noob. I really want to learn how to obtain the world matrix or camera in the game, and I am eager to write my first Hacker project through these memory addresses. For example, functions such as ESP

**Comment by DoPaminexL** [comment]
> I cannot recreate that error. You could try including imgui.h in Game.h Note that this code isn't updated to the newest version of the game.

I am a beginner Noob. I really want to learn how to obtain the world matrix or camera in the game, and I am eager to write my first Hacker project through these memory addresses. For example, functions such as ESP

**Comment by DoPaminexL** [comment]
> I cannot recreate that error. You could try including imgui.h in Game.h Note that this code isn't updated to the newest version of the game.

Yes, Hacker, after including imgui, the compilation was successful

**Comment by UtterVitriol** [comment]
I am also noob. lol I haven't gotten quite that far myself.

**Comment by UtterVitriol** [comment]
.

**Comment by DoPaminexL** [comment]
Do you have any better examples of ue4hacker

**Comment by UtterVitriol** [comment]
My deep rock repo has some detours. But, the time investment for me hasn't been worth it to learn more yet. You'll probably want to look into making an sdk with the ue4 source. I don't really have any experience with that though.
